In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [2]:
import random
np.random.seed(123)

arr = np.random.rand(12)
meana = arr.mean()

d_arr = []
for i in range(len(arr)):
    if arr[i-1] > meana:
        d_arr.append(float(arr[i-1]))
print(f"Сгенерированный массив: \n", arr, '\n')
print(f"Среднее арифмеическое получившегося массива:", meana, '\n')
print(f"Элементы, больше среднего арифметического: \n", d_arr)

Сгенерированный массив: 
 [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752 0.34317802 0.72904971] 

Среднее арифмеическое получившегося массива: 0.542851771107355 

Элементы, больше среднего арифметического: 
 [0.7290497073840416, 0.6964691855978616, 0.5513147690828912, 0.7194689697855631, 0.9807641983846155, 0.6848297385848633]


**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [3]:
np.random.seed(23)

arr2_size = 20

arr2 = [np.random.randint(0, 11) for _ in range(arr2_size)]

#Определить количество элементов, отличающихся от минимального на 5.
diff_num = 0
for _ in range(len(arr2)):
    if arr2[_] == np.min(arr2) + 5:
        diff_num += 1
print("В сгенерированном массиве", diff_num, "элемента(-ов), отличающихся от минимального на 5.")

#Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

arr2_odds = []
for i in range(len(arr2[0::2])):
    if arr2[0::2][i] % 2 == 0:
        arr2_odds.append(arr2[0::2][i])

print("Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах, равно", float(np.mean(arr2_odds)))

В сгенерированном массиве 3 элемента(-ов), отличающихся от минимального на 5.
Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах, равно 5.5


**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [4]:
arr3_size = 25
arr3 = [np.random.randint(0, 11) for _ in range(arr3_size)]
arr3_matrix = np.array(arr3).reshape(5, 5)

In [5]:
#Сгенерированная матрица:
arr3_matrix

array([[ 9,  3,  1,  7,  4],
       [ 1,  1,  4,  6,  7],
       [ 3, 10,  6,  9,  2],
       [10,  3,  0,  8,  6],
       [ 6,  0,  5,  6,  0]])

In [6]:
#Возвести в квадрат максимальный элемент матрицы.
max_r = max(arr3_matrix, key=max)
maxarr = float(np.max(max_r))

arr3_matrix[np.where(arr3_matrix == maxarr)] = arr3_matrix[np.where(arr3_matrix == maxarr)] **2
arr3_matrix

array([[  9,   3,   1,   7,   4],
       [  1,   1,   4,   6,   7],
       [  3, 100,   6,   9,   2],
       [100,   3,   0,   8,   6],
       [  6,   0,   5,   6,   0]])

In [7]:
#Все четные числа заменить на 0.
arr31 = arr3_matrix.copy()

i, j = 0, 0
for i in range(5):
    for j in range(5):
        if arr31[j][i] % 2 == 0:
            arr31[j][i] = 0

arr31

array([[9, 3, 1, 7, 0],
       [1, 1, 0, 0, 7],
       [3, 0, 0, 9, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [8]:
#Генерируем матрицу
b_size = 25
b_list = [np.random.randint(-5, 6) for _ in range(b_size)]
b_matrix = np.array(b_list).reshape(5, 5)
b_matrix

array([[-3, -5, -2, -5,  1],
       [-3, -3,  0,  2,  4],
       [-1,  5,  2,  2,  5],
       [-2,  0,  0,  1, -1],
       [ 1,  3,  0, -5, -1]])

In [9]:
#Заменяем отрицательные элементы матрицы на число отрицательных элементов в строке, в которой они находятся.

count_l = [0, 0, 0, 0, 0]

for i in range(b_matrix.shape[0]):
    for j in range(b_matrix.shape[1]):
        if b_matrix[i][j] < 0:
            count_l[i] += 1

for i in range(b_matrix.shape[0]):
    for j in range(b_matrix.shape[1]):
        if b_matrix[i][j] < 0:
            b_matrix[i][j] = count_l[i]

print('Получаем следующую матрицу')
b_matrix

Получаем следующую матрицу


array([[4, 4, 4, 4, 1],
       [2, 2, 0, 2, 4],
       [1, 5, 2, 2, 5],
       [2, 0, 0, 1, 2],
       [1, 3, 0, 2, 2]])

# Pandas

In [10]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [12]:
df.head(2)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [13]:
#Какой была максимальная цена билета? Медиана?
df['fare'].describe()

count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: fare, dtype: float64

Таким образом, максимальная цена билета составила 512,33 денежных единицы (вероятно, доллара), а медианная - 14,45 ден. ед. К аналогичным выводам можно прийти через функции .medean() & .max() :

In [14]:
print('Максимальная стоимость билета составила', float(round(df['fare'].max(), 2)), 'денежных единиц, а \nМедианная -', float(round(df['fare'].median(), 2)), 'ден. ед.')

Максимальная стоимость билета составила 512.33 денежных единиц, а 
Медианная - 14.45 ден. ед.


In [15]:
#Какова доля выживших?
df['survived'].value_counts(normalize=True)

survived
0    0.618029
1    0.381971
Name: proportion, dtype: float64

In [16]:
print('Таким образом, доля выживших составила', round(float(df['survived'].value_counts(normalize=True)[1]), 4))

Таким образом, доля выживших составила 0.382


In [17]:
#Сколько мужчин / женщин находилось на борту?
print('На борту находилось', df['sex'].value_counts()['male'], 'мужчин и', df['sex'].value_counts()['female'], 'женщин.')

На борту находилось 843 мужчин и 466 женщин.


**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [18]:
#Выведите распределение переменной pclass для мужчин и женщин.
df_scl = df.pivot_table(index='pclass', 
                      columns='sex',
                      values='age',
                      aggfunc='count')
df_scl

sex     female  male
pclass              
1          133   151
2          103   158
3          152   349

In [19]:
#Сколько мужчин было в первом классе?
#Сколько женщин было в третьем классе?

print("В первом классе было", df_scl['male'].loc[1], 'мужчин, а в третьем классе находилось', df_scl['female'].loc[3], 'женщин')

В первом классе было 151 мужчин, а в третьем классе находилось 152 женщин


+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [20]:
def age_gr(age):
    if age < 30:
        return 1
    elif age >= 30 and age < 60:
        return 2
    elif age >= 60:
        return 3
    else:
        return 0 #добавили на случай, если встретятся какие-то иные значения, например, nan

In [21]:
df['age_group'] = df['age'].apply(age_gr)
df.head(2)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   

                         home.dest  age_group  
0                     St Louis, MO          1  
1  Montreal, PQ / Chesterville, ON          1

In [22]:
df.loc[df['age_group'] == 0]['age'].unique()

array([nan])

получили, что в датасете имеются несколько строк (более 250), где пропущены значения возраста, следовательно, и <code>age_group</code> не может быть полностью заполнено. <br>
Однако, в случае необходимости, можно определить примерную группу исходя из других записей, со схожими данными по столбцам класса, стоимости билета, порта и home.dest

**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [23]:
dict = pd.read_csv('yob2023.txt', sep=',')
dict.head()

name  sex_d   number
0     Olivia      F    15270
1       Emma      F    13527
2  Charlotte      F    12596
3     Amelia      F    12311
4     Sophia      F    11944

In [24]:
def find_name(full_name, name_list):
    for name in name_list:
        if name in full_name:
            return name
    return np.nan

In [25]:
name_list = dict['name'].unique()
df['first_name'] = df['name'].apply(lambda x: find_name(x, name_list))
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  age_group first_name  
0                     St Louis, MO          1      Elisa  
1  Montreal, PQ / Chesterville, ON          1    Allison  
2  Montreal, PQ / Chesterville, ON          1    Allison  
3  Montreal, PQ / Chesterville, ON          2    Allison  
4  Montreal, PQ / Chesterville, ON          1    Allison

In [28]:
#проверим, есть ли пустые значения
df.loc[df['first_name'].isna() == True].shape[0]

27

In [29]:
#проверим, сколько из этих строк - уникальны (по ним мы сможем судить о частоте таких имен и о том, 
#нужно ли их вытаскивать вручную в столбец first_name для исследования)
df.loc[df['first_name'].isna() == True]['name']

648                    Assaf, Mr. Gerios
651                 Attalah, Mr. Sleiman
663                    Balkic, Mr. Cerin
673                  Betros, Mr. Tannous
698                 Cacic, Mr. Jego Grga
716          Chronopoulos, Mr. Apostolos
740                  Culumovic, Mr. Jeso
741                    Daher, Mr. Shedid
775                  Doharr, Mr. Tannous
805                      Foo, Mr. Choong
844       Hakkarainen, Mr. Pekka Pietari
863               Hendekovic, Mr. Ignjac
876                     Ilieff, Mr. Ylio
909                  Jussila, Mr. Eiriik
941                Krekorian, Mr. Neshan
1064                  Niskanen, Mr. Juha
1128    Petroff, Mr. Pastcho ("Pentcho")
1132              Plotcharsky, Mr. Vasil
1133                   Pokrnic, Mr. Mate
1139                     Rekic, Mr. Tido
1203                   Sivic, Mr. Husein
1212                Slabenoff, Mr. Petco
1219                  Spector, Mr. Woolf
1228                  Stranden, Mr. Juho
1248            

Мы видим, что данные имена довольно редкие и можем говорить об отсутствии их влияния на исследование

In [30]:
df.query('sex == "female"')['first_name'].value_counts().head(2)

first_name
Elizabeth    25
Mary         23
Name: count, dtype: int64

In [31]:
df.query('sex == "male"')['first_name'].value_counts().head(2)

first_name
Jo       101
James     25
Name: count, dtype: int64

Самое популярное женское имя - Элизабет (встречается 25 раз) (почти столько же на титанике было женщин с именем Мари - 23) <br>
Самое популярное мужское имя - Джо (встретилось 101 раз); следующее же за ним по популярности имя - Джеймс, однако почти вчетверо меньше упоминаний о нем (25)

**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [32]:
df.head(1)

pclass  survived                           name     sex   age  sibsp  \
0       1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   

   parch ticket      fare cabin embarked boat  body     home.dest  age_group  \
0      0  24160  211.3375    B5        S    2   NaN  St Louis, MO          1   

  first_name  
0      Elisa

In [34]:
#Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
df.query('embarked == "C" and age > 50')

pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                               Lurette, Miss. Elise   
215       1         0                         Newell, Mr. Arthur Webster   
221       1         0                     Ostby, Mr. Engelhart Cornelius   
233       1         1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
246       1         0                             Rothschild, Mr. Martin   
247       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
252       1         0                         Ryerson, Mr. Arthur Larned   
264       1         1                Simonius-Blumer, Col. Oberst Alfons   
267       1         0                            Smith, Mr. James Clinch   
276       1         0                      Spencer, Mr. William Augustus   
280       1         1                    Stengel, Mr. Charles Emil Henry   
282       1         1    Stephenson, Mrs. Walter Bertram (Martha Eustis)   
303       1         0                           Warren, Mr. Frank Manley   
304       1         1   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
308       1         1              White, Mrs. John Stuart (Ella Holmes)   
316       1         0                        Williams, Mr. Charles Duane   

        sex   age  sibsp  parch    ticket      fare            cabin embarked  \
9      male  71.0      0      0  PC 17609   49.5042              NaN        C   
43   female  60.0      0      0     11813   76.2917              D15        C   
48   female  53.0      0      0  PC 17606   27.4458              NaN        C   
50   female  58.0      0      1  PC 17755  512.3292      B51 B53 B55        C   
78   female  64.0      0      2  PC 17756   83.1583              E45        C   
104  female  54.0      1      0     36947   78.2667              D20        C   
123    male  60.0      1      1     13567   79.2000              B41        C   
135    male  71.0      0      0  PC 17754   34.6542               A5        C   
136    male  53.0      0      0    113780   28.5000              C51        C   
174    male  58.0      0      0     11771   29.7000              B37        C   
186  female  55.0      0      0    112377   27.7208              NaN        C   
192  female  58.0      0      0  PC 17569  146.5208              B80        C   
215    male  58.0      0      2     35273  113.2750              D48        C   
221    male  65.0      0      1    113509   61.9792              B30        C   
233  female  56.0      0      1     11767   83.1583              C50        C   
246    male  55.0      1      0  PC 17603   59.4000              NaN        C   
247  female  54.0      1      0  PC 17603   59.4000              NaN        C   
252    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C   
264    male  56.0      0      0     13213   35.5000              A26        C   
267    male  56.0      0      0     17764   30.6958               A7        C   
276    male  57.0      1      0  PC 17569  146.5208              B78        C   
280    male  54.0      1      0     11778   55.4417             C116        C   
282  female  

In [38]:
#Выведите данные о всех женщинах младше 20 и старше 50 лет.
df.query('sex == "female" and (age < 20 or age > 50)')

pclass  survived                                               name  \
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
...      ...       ...                                                ...   
1265       3         0                          Van Impe, Miss. Catharina   
1273       3         0                 Vander Planke, Miss. Augusta Maria   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex   age  sibsp  parch    ticket      fare    cabin embarked boat  \
2     female   2.0      1      2    113781  151.5500  C22 C26        S  NaN   
6     female  63.0      1      0     13502   77.9583       D7        S   10   
8     female  53.0      2      0     11769   51.4792     C101        S    D   
11    female  18.0      1      0  PC 17757  227.5250  C62 C64        C    4   
27    female  19.0      1      0     11967   91.0792      B49        C    7   
...      ...   ...    ...    ...       ...       ...      ...      ...  ...   
1265  female  10.0      0      2    345773   24.1500      NaN        S  NaN   
1273  female  18.0      2      0    345764   18.0000      NaN        S  NaN   
1279  female  14.0      0      0    350406    7.8542      NaN        S  NaN   
1300  female  15.0      1      0      2659   14.4542      NaN        C  NaN   
1304  female  14.5      1      0      2665   14.4542      NaN        C  NaN   

       body                        home.dest  age_group first_name  
2       NaN  Montreal, PQ / Chesterville, ON          1    Allison  
6       NaN                       Hudson, NY          3       Theo  
8       NaN              Bayside, Queens, NY          2  Charlotte  
11      NaN                     New York, NY          1  Madeleine  
27      NaN                     Dowagiac, MI          1      Helen  
...     ...                              ...        ...        ...  
1265    NaN                              NaN          1        Van  
1273    NaN                              NaN          1      Maria  
1279    NaN                              NaN          1     Amanda  
1300    NaN                              NaN          1      Alexa  
1304  328.0                              NaN          1         Mi  

[135 rows x 16 columns]

In [42]:
#Сколько пассажиров старше 70 лет было на борту?
print("На борту было", df.query('age > 70').shape[0], "пассажиров старше 70 лет.")

На борту было 6 пассажиров старше 70 лет.


**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [45]:
df.groupby('sex')['age'].mean()

sex
female    28.687071
male      30.585233
Name: age, dtype: float64

In [49]:
#Посчитайте средний возраст среди мужчин и среди женщин
print("Средний возраст женщин составляет", round(df.groupby('sex')['age'].mean().loc['female'], 2),
      "лет, а средний возраст мужчин -",  round(df.groupby('sex')['age'].mean().loc['male'], 2), "лет" )

Средний возраст женщин составляет 28.69 лет, а средний возраст мужчин - 30.59 лет


In [64]:
#Посчитайте доли выживших в различных возрастных группах (новый признак AgeGroup).
df_age_srvd = df.query('age_group != 0')

df_age_survived = df_age_srvd.groupby('age_group')['survived'].value_counts(normalize=True)
df_age_survived.loc[pd.IndexSlice[:, 1]]

age_group
1    0.409490
2    0.416476
3    0.300000
Name: proportion, dtype: float64

In [66]:
print('В первой возрастной группе (до 30 лет) выжил 40,95% пассажиров \nВо второй - 41,65%, а в третьей - 30%')

В первой возрастной группе (до 30 лет) выжил 40,95% пассажиров 
Во второй - 41,65%, а в третьей - 30%


In [83]:
#Найдите максимальную стоимость билета в каждом из ценовых классов.
df.head(1)

pclass  survived                           name     sex   age  sibsp  \
0       1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   

   parch ticket      fare cabin embarked boat  body     home.dest  age_group  \
0      0  24160  211.3375    B5        S    2   NaN  St Louis, MO          1   

  first_name  
0      Elisa

In [82]:
df.groupby('pclass')['fare'].max()

pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64

Максимальная стоимость билета в первом классе составила 512,33 де. ед., во второом - 73,5 ден. ед., а в третьем - 69,55 ден. ед.

**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [84]:
#Посчитайте средний возраст среди мужчин и среди женщин

df.pivot_table(index='sex',
              values='age',
              aggfunc='mean')

age
sex              
female  28.687071
male    30.585233

In [88]:
#Посчитайте доли выживших в различных возрастных группах (новый признак AgeGroup).
pd.crosstab(df.query('age_group != 0')['age_group'], df['survived'], values='survived', aggfunc='count', normalize='index')

survived          0         1
age_group                    
1          0.590510  0.409490
2          0.583524  0.416476
3          0.700000  0.300000

In [92]:
#Найдите максимальную стоимость билета в каждом из ценовых классов.
df.pivot_table(index='pclass',
              values='fare',
              aggfunc=lambda x: round(x.max(), 2).squeeze())

fare
pclass        
1       512.33
2        73.50
3        69.55